== Render Applications using ApplicationSet

Until now you have applied day 2 operations by creating single Applications by hand. However there is an easier way to render those apps using ApplicationSets.

Checkout to *main-day2* branch to take a look:

[.lines_7]
[.console-input]
[source, shell,subs="+macros,+attributes"]
----
git branch # main
git checkout -b main-day2   
----  

Navigate to the ApplicationSet folder and take a look to the newly added day2-sno-as file.

[.lines_7]
[.console-input]
[source, shell,subs="+macros,+attributes"]
----
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: day2-sno-<name>
  namespace: openshift-operators
spec:
  generators:
  - git:
      repoURL: https://github.com/<your_user>/workshop-gitops-content-deploy.git
      revision: sno-<name>-setup
      files:
      - path: "cluster-definition/**/cluster.json"
  template:
    metadata:
      name: 'day2-{{cluster.name}}-a'
    spec:
      project: '{{project}}'
      source:
        repoURL: https://github.com/<your_user>/workshop-gitops-content-deploy.git
        targetRevision: sno-<name>-setup
        path: cluster-addons/charts/day2
      destination:
        server: '{{cluster.address}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true   
----  

This ApplicationSet render N configurations for N managed clusters to apply day 2 configurations by creating Application on argocd-infra instance on managed cluster.

If you navigate to the charts folder, you will see you are not creating objects itself but Applications. Let's test it.

Go back to your working branch (*sno-<name>-setup*) and merge it with *main-day2* branch. You must see this extra ApplicationSet plus a new day2 folder on charts.

Replaced with your cluster configuration data as required.

Then push to your working branch.

Finally, navigate to argo hub instance and see the recently created ApplicationSet, then navigate to argocd-infra instance on managed cluster and see the Applications managed by the Application
generated by ApplicationSet.
