== Configure namespace

Part of day 2 configurations are setting namespace scoped configurations for managing networking and quotas for apps, as well as setting RBAC.

In this example, based on the last app deployment we are going to deploy some resources and objects quotas by namespace.

Therefore we are going to set some cluster and local roles.

Finally we are going to deploy a Network Policy to prevent traffic to the app. You can try enabling/disabling this feature to see how traffic is allowed and denied.

[.lines_7]
[.console-input]
[source, java,subs="+macros,+attributes"]
----
    helm:
      parameters:
        - name: global.oauth.enabled
          value: 'true'
        - name: oauth.oauth.keycloak.clientid
          value: myclient-<name>
        - name: oauth.oauth.keycloak.issuer
          value: >-
            https://keycloak-keycloak.apps.argo-hub.<domain>>.opentlc.com/realms/myrealm-<name>
        - name: oauth.oauth.keycloak.data
          value: "your keycloak secret" *
        - name: oauth.oauth.ldap.sync.ldap_url
          value: 'ldap://<nodeport:port>'        
        - name: global.nmstate.enabled
          value: 'false'
        - name: global.monitoring.enabled
          value: 'true'     
        - name: global.namespace.enabled
          value: 'true' 
        - name: namespace.networkpolicy.enabled
          value: 'true'                                   
        - name: global.bookinfo.enabled
          value: 'true'          
        - name: global.operators.enabled
          value: 'true'      
        - name: operators.operators.servicemesh.enabled
          value: 'true' 
        - name: operators.operators.jaeger.enabled
          value: 'true'
        - name: operators.operators.kiali.enabled
          value: 'true'
        - name: operators.operators.tekton.enabled
          value: 'true'   
        - name: operators.operators.nmstate.enabled
          value: 'true' 
        - name: operators.istio.enabled
          value: 'true'                                                              
---- 

Once you update the Application you want be able to create more than 4 pods in namespace app. Try to update replicas deployment to see if quota has been correctly applied by argo.

# Add screenshot

Then if you try to navigate to app route you will see you are not allowd:

# Add screenshot

Then disable network policy and verify how you have traffic access:

# Add screenshot
