== Configure monitoring

Now we are going to deploy some basic configuration about monitoring.

In Openshift 4 monitoring is enabled by default however there are lots of configurations we can modify and configure non default user defined projects monitoring stack.

You can take a look to the monitoring documentation https://docs.openshift.com/container-platform/4.12/monitoring/enabling-monitoring-for-user-defined-projects.html[here].
In the first place we are going to enable user-defined projects monitoring. Then we will create an example app, with a Service Monitor and a custom Prometheus Rule.

Go to your working branch and create a file called *values-monitoring.yaml*:

[.lines_7]
[.console-input]
[source, shell,subs="+macros,+attributes"]
----
monitoring:
  enabled: true # Enable dependency   
---- 

Then create the Application on argocd-infra instance:

[.lines_7]
[.console-input]
[source, shell,subs="+macros,+attributes"]
----
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sno-<name>-monitoring
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    helm:
      valueFiles:
        - values-monitoring.yaml
    path: .
    repoURL: 'https://github.com/<your_user>/helm-infra-gitops-workshop.git'
    targetRevision: sno-<name>
  syncPolicy:
    automated:
      prune: true
      selfHeal: true                                                            
---- 

This is an easy configuration as sync waves are not a must because objects don't have direct dependencies and they do not affect to existing configurations.

Then navigate to Openshift console to verify those objects exist on the cluster and if Service Monitor is scraping your metrics properly:

*Add how to*