== Configure Identity Providers

As you can see, there is already a local identity provider configured but we want to override current users and integrate with other identity providers like LDAP Free Ipa provider and Keycloak.

For configuring Identity Providers on Openshift you just need to modify the existing https://docs.openshift.com/container-platform/4.12/authentication/identity_providers/configuring-htpasswd-identity-provider.html[Oauth] resource with the provider and its configuration data.

For some of them we just need to set up the integration while for others like LDAP apart from the integration agains the server we also need to synchronize groups and users.

Let's deploy the oauth resources required and verify how groups are synchronized.

*Reminder*: keycloak and FreeIPA server are running on argo hub cluster.

First we need to take a look to *oauth* chart values. As you can see you need to define some missing values for each managed cluster. You can do this by setting those on chart values file,
 setting them as parametes or defining a new values file for your deployment.

Go to your working branch and create a file called *values-oauth.yaml*:

[.lines_7]
[.console-input]
[source, shell,subs="+macros,+attributes"]
----
oauth:
  enabled: true # Enable dependency
  keycloak: # Update chart values
    clientid: myclient-<name>
    issuer: https://keycloak-keycloak.apps.argo-hub.<domain>.opentlc.com/realms/myrealm-<name>
    data: <your_keycloak_secret_data>
  ldap:
    sync:
      ldap_url: 'ldap://<ip>:<nodeport>'
     
---- 

Then create a new Application to apply this operation:

[.lines_7]
[.console-input]
[source, shell,subs="+macros,+attributes"]
----
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: day-2-sno-<name>
  namespace: openshift-operators
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    helm:
      valueFiles:
        - values-oauth.yaml
    path: .
    repoURL: 'https://github.com/<your_user>/helm-infra-gitops-workshop.git'
    targetRevision: sno-<name>
  syncPolicy:
    automated:
      prune: true
      selfHeal: true   
---- 

*Keycloack secret*: Login to argo-hub console, find keycloack url, login as admin/admin, navigate to your realm, then go to your client and  find your secret on Credentials tab.

If you take a look to the helm charts you will notice we do not only need to update oauth but create others resources needed for integration like secrets, cm and cron job for syncying groups.

Sync waves are needed to make sure those resources like secrets and cm for authentication exists when we update Oauth config, otherwise openshift-authentication will become Degraded.
When you update oauth values, and update existing Application you can notice how they are created in phases and not all at the same time.

For groups syncying, cron job shows last 5 executions, including the state according to the result (failed or success).

Furthermore you can notice some resources with no status (white fields). Those resources are created by Openshift for configuration issues but they are not managed by argo, that's why argo is not tracking them.
https://argo-cd.readthedocs.io/en/stable/user-guide/resource_tracking/[Resource tracking] has been set to annotation+label on argo instance.

Once every resource is deployed, verify authentication cluster operator is OK, logout and log in back. Then you should see new identity providers listed.

[.lines_7]
[.console-input]
[source, shell,subs="+macros,+attributes"]
----
oc get co

oc get oauth cluster -o yaml 
----

You can try keycloack server with myuser-<name>/myuser-<name>.

You can try login to LDAP server with user paul/"" who is an admin user.
You can try login to LDAP server with user mark/"" who is an viewer user.
