== Configure operators

Once authentication is configured, we are going to deploy some operators. Operatos helm charts use range values so we can define as many operators as we want on values section.

We are going to deploy tekton, kiali, jaeger, servicemesh and nmstate operator. Furthermore we are going to deploy Service Mesh Control Plane and Member Roll and an example application called bookinfo for service mesh.

[.lines_7]
[.console-input]
[source, java,subs="+macros,+attributes"]
----
    helm:
      parameters:
        - name: global.oauth.enabled
          value: 'true'
        - name: oauth.oauth.keycloak.clientid
          value: myclient-<name>
        - name: oauth.oauth.keycloak.issuer
          value: >-
            https://keycloak-keycloak.apps.argo-hub.<domain>>.opentlc.com/realms/myrealm-<name>
        - name: oauth.oauth.keycloak.data
          value: "your keycloak secret" *
        - name: oauth.oauth.ldap.sync.ldap_url
          value: 'ldap://<nodeport:port>'        
        - name: global.nmstate.enabled
          value: 'false'
        - name: global.monitoring.enabled
          value: 'false'     
        - name: global.namespace.enabled
          value: 'false'                         
        - name: global.bookinfo.enabled
          value: 'true'          
        - name: global.operators.enabled
          value: 'true'      
        - name: operators.operators.servicemesh.enabled
          value: 'true' 
        - name: operators.operators.jaeger.enabled
          value: 'true'
        - name: operators.operators.kiali.enabled
          value: 'true'
        - name: operators.operators.tekton.enabled
          value: 'true'   
        - name: operators.operators.nmstate.enabled
          value: 'true' 
        - name: operators.istio.enabled
          value: 'true'                                                              
---- 

Helm charts includes subcription definition for each operator in the last version available in stable channel, while Install Plan is set to Automatic so we do not need to manually approve installation.
This is all set in values as parameters so we can use these charts for different installation methods by overriding those values.

In this case sync waves and healthchecks are very important as for being able to deploy bookinfo app, operator must be installed in the first place but also mesh should be configured.

If sync waves are not configured properly it will try to create reosurces whose api still doesn't exist in the cluster.

Once operators are installed you can view them as well with the Install Plan managed by argo:

* add screenshot *

Then you can try to uninstall an operator by disabling it from helm chart, for example tekton operator as we are not planning to use it:

[.lines_7]
[.console-input]
[source, java,subs="+macros,+attributes"]
----
    helm:
      parameters:
        - name: global.oauth.enabled
          value: 'true'
        - name: oauth.oauth.keycloak.clientid
          value: myclient-<name>
        - name: oauth.oauth.keycloak.issuer
          value: >-
            https://keycloak-keycloak.apps.argo-hub.<domain>>.opentlc.com/realms/myrealm-<name>
        - name: oauth.oauth.keycloak.data
          value: "your keycloak secret" *
        - name: oauth.oauth.ldap.sync.ldap_url
          value: 'ldap://<nodeport:port>'        
        - name: global.nmstate.enabled
          value: 'false'
        - name: global.monitoring.enabled
          value: 'false'     
        - name: global.namespace.enabled
          value: 'false'                         
        - name: global.bookinfo.enabled
          value: 'true'          
        - name: global.operators.enabled
          value: 'true'      
        - name: operators.operators.servicemesh.enabled
          value: 'true' 
        - name: operators.operators.jaeger.enabled
          value: 'true'
        - name: operators.operators.kiali.enabled
          value: 'true'
        - name: operators.operators.tekton.enabled
          value: 'false'   
        - name: operators.operators.nmstate.enabled
          value: 'true' 
        - name: operators.istio.enabled
          value: 'true'                                                              
---- 

Then argo should reconcile resources according to the new configuration.