== Day 2

As you can see, there is already a local identity provider configured we want to override current users and integrate with other identity providers like LDAP Free Ipa provider and keycloak.

For LDAP apart form integrating against the server we also need to synchronize groups and users.

Let's deploy the oauth resources required and verify how groups are synchronized.

Disclaimer: keycloak and FreeIPA server are running on argo hub cluster.

[.lines_7]
[.console-input]
[source, java,subs="+macros,+attributes"]
----
    helm:
      parameters:
        - name: global.oauth.enabled
          value: 'true'
        - name: global.oauth.oauth.keycloak.clientid
          value: 'myclient-1'     
        - name: global.oauth.oauth.keycloak.issuer
          value: 'https://keycloak-keycloak.apps.argo-hub.sandbox1444.opentlc.com/realms/myrealm-1'           
        - name: global.oauth.oauth.keycloak.data
          value: ''
        - name: global.oauth.oauth.ldap.sync.ldap_url
          value: 'ldap://10.0.210.36:32106'
        - name: global.operators.enabled
          value: 'false'
        - name: global.nmstate.enabled
          value: 'false'
        - name: global.monitoring.enabled
          value: 'false'     
        - name: global.namespace.enabled
          value: 'false'                         
        - name: global.bookinfo.enabled
          value: 'false'     
        - name: operators.nmstate.enabled
          value: 'false'      
---- 

If you take a look to the helm charts you will notice we do not only need to update oauth but create others resources needed for integration like secrets, cm and cron job for syncying groups.

Sync waves are needed to make sure those resources like secrets and cm for authentication exists when we update Oauth config, otherwise openshift-authentication will become Degraded.
When you update oauth values, and update existing Application you can notice how they are created in phases and not all at the same time.

For groups syncying, cron job shows last 5 executions, including the state according to the result (failed or success).

Furthermore you can notice some resources with no status (white fields). Those resources are created by Openshift for configuration issues but they are not managed by argo, that's why argo is not tracking them.

Once every resource is deployed, verify authentication cluster operator is OK, logout and log in back. Then you should see new identity providers listed.

[.lines_7]
[.console-input]
[source, java,subs="+macros,+attributes"]
----
oc get co
----