== Configure monitoring

Now we are going to deploy some basic configuration about monitoring.

In Openshift 4 monitoring is enabled by default however there are lots of configurations we can modify and configure non default user defined projects monitoring stack.

You can take a look to the monitoring documentation https://docs.openshift.com/container-platform/4.12/monitoring/enabling-monitoring-for-user-defined-projects.html[here].
I
n the first place we are going to enable user-defined projects monitoring. Then we will create an example app, with a Service Monitor and a custom Prometheus Rule.

[.lines_7]
[.console-input]
[source, java,subs="+macros,+attributes"]
----
    helm:
      parameters:
        - name: global.oauth.enabled
          value: 'true'
        - name: oauth.oauth.keycloak.clientid
          value: myclient-<name>
        - name: oauth.oauth.keycloak.issuer
          value: >-
            https://keycloak-keycloak.apps.argo-hub.<domain>.opentlc.com/realms/myrealm-<name>
        - name: oauth.oauth.keycloak.data
          value: "your keycloak secret" *
        - name: oauth.oauth.ldap.sync.ldap_url
          value: 'ldap://<nodeport:port>'        
        - name: global.nmstate.enabled
          value: 'false'
        - name: global.monitoring.enabled
          value: 'true'     
        - name: global.namespace.enabled
          value: 'false'                         
        - name: global.bookinfo.enabled
          value: 'true'          
        - name: global.operators.enabled
          value: 'true'      
        - name: operators.operators.servicemesh.enabled
          value: 'true' 
        - name: operators.operators.jaeger.enabled
          value: 'true'
        - name: operators.operators.kiali.enabled
          value: 'true'
        - name: operators.operators.tekton.enabled
          value: 'true'   
        - name: operators.operators.nmstate.enabled
          value: 'true' 
        - name: operators.istio.enabled
          value: 'true'                                                              
---- 

This is an easy configuration as sync waves are not a must because objects don't have direct dependencies and they do not affect to existing configurations.

Then navigate to Openshift console to verify those objects exist on the cluster and if Service Monitor is scraping your metrics properly:

# Add how to